# 86SR ( 5.0000e-09)
#  Excitation  flag   Halflife  Mode    Daughter Ex flag   Intensity          Q
P      2672.89  -        5e-09
                                     IT            0               1
P      2857.41  -        5e-09
                                     IT            0               1
P      2956.09  -     4.55e-07
                                     IT            0               1
P      3055.87  -        5e-09
                                     IT            0               1
P      3185.29  -        5e-09
                                     IT            0               1
P      3291.46  -        5e-09
                                     IT            0               1
P       3482.3  -        5e-09
                                     IT            0               1
P       3665.3  -        5e-09
                                     IT            0               1
P      3765.74  -        5e-09
                                     IT            0               1
P       3973.1  -        5e-09
                                     IT            0               1
P       4148.5  -        5e-09
                                     IT            0               1
P       4600.6  -        5e-09
                                     IT            0               1
P       5012.7  -        5e-09
                                     IT            0               1
P       5425.6  -        5e-09
                                     IT            0               1
