# 86NB ( 5.6000e+01)
#  Excitation  flag   Halflife  Mode    Daughter Ex flag   Intensity          Q
P            0 +Y           56
                               BetaPlus            0             0.5
                                     IT            0             0.5
                               BetaPlus            0  -          100      8835.77
P        49.96 +X      6.8e-08
                                     IT            0               1
